### PR TITLE
MAJOR BUG FIXES IN SPELLING

### PR DESCRIPTION
**Pull request by unlimitedcoder2**
There was a spelling mistake in the file `Website/PlayerServers/EnglishUk/dashboard.php`
As a person from the UK I noticed the mistake and have fixed it for you/

### CODE REVIEW

**Comment by DebitCardz** [comment]
This is vital to the survival of the CubedCraft Network, this merge must be accepted at once.

**Review by DebitCardz — APPROVED** [review]
This is well needed.

**Review by needvoid — APPROVED** [review]
Yes

**Comment by JacobWennebro** [comment]
This is a vital fix and should be merged immediately.

**Review by needvoid — APPROVED** [review]

**Comment by DebitCardz** [comment]
please fix this quickly, i can't live on knowing these changes have yet to be implemented into the cubedcraft network server.

**Review by DebitCardz — APPROVED** [review]
great stuff from a great man.

**Comment by DebitCardz** [comment]
Still waiting for this PR to be merged into master.

**Review by joshrblx — APPROVED** [review]
yes.

**Comment by unlimitedcoder2** [comment]
Pog

**Comment by DebitCardz** [comment]
LGTM

**Pull request closed without merging**
